// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shapr3D_Converter.Models;

namespace Shapr3D_Converter.Models.Migrations
{
    [DbContext(typeof(Shapr3dDbContext))]
    partial class Shapr3dDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Shapr3D_Converter.Models.ModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileBytes")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ObjConverted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ObjFileBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("OriginalPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StepConverted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("StepFileBytes")
                        .HasColumnType("BLOB");

                    b.Property<bool>("StlConverted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("StlFileBytes")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ModelEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
